/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BasketType = { 'woodenCrate' : null } |
  { 'wickerBasket' : null } |
  { 'giftBox' : null };
export interface Cart {
  'basketType' : BasketType,
  'userId' : string,
  'packingType' : PackType,
  'size' : Size,
  'messageCard' : [] | [string],
  'items' : Array<CartItem>,
}
export interface CartItem {
  'wrappingOption' : [] | [string],
  'customMessage' : [] | [string],
  'quantity' : bigint,
  'packId' : string,
}
export interface CatalogFilters {
  'outOfStock' : [] | [boolean],
  'priceRange' : [] | [{ 'max' : bigint, 'min' : bigint }],
  'searchTerm' : [] | [string],
  'category' : [] | [Category],
}
export type Category = { 'anniversary' : null } |
  { 'custom' : null } |
  { 'festive' : null } |
  { 'birthday' : null } |
  { 'wellness' : null } |
  { 'sympathy' : null } |
  { 'corporate' : null };
export interface DeliveryAddress {
  'id' : string,
  'street' : string,
  'city' : string,
  'name' : string,
  'state' : string,
  'phone' : string,
  'pincode' : string,
}
export type ExternalBlob = Uint8Array;
export interface GiftItem {
  'id' : string,
  'name' : string,
  'description' : string,
  'category' : Category,
  'price' : bigint,
  'images' : Array<ExternalBlob>,
}
export interface GiftPack {
  'id' : string,
  'basketType' : BasketType,
  'title' : string,
  'size' : Size,
  'description' : string,
  'category' : Category,
  'items' : Array<GiftItem>,
  'price' : bigint,
  'images' : Array<ExternalBlob>,
}
export interface Order {
  'id' : string,
  'basketType' : BasketType,
  'status' : OrderStatus,
  'deliveryAddress' : DeliveryAddress,
  'userId' : string,
  'packingType' : PackType,
  'createdAt' : Time,
  'size' : Size,
  'messageCard' : [] | [string],
  'totalAmount' : bigint,
  'items' : Array<CartItem>,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export type PackType = { 'ribbonColor1' : null } |
  { 'ribbonColor2' : null } |
  { 'wrapStyle1' : null } |
  { 'wrapStyle2' : null };
export type Size = { 'large' : null } |
  { 'small' : null } |
  { 'medium' : null };
export type Time = bigint;
export interface UserProfile {
  'principal' : Principal,
  'name' : string,
  'email' : string,
  'phone' : string,
  'defaultAddress' : DeliveryAddress,
}
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createOrUpdateUserProfile' : ActorMethod<
    [string, string, string, DeliveryAddress],
    UserProfile
  >,
  'createOrder' : ActorMethod<
    [
      string,
      Array<CartItem>,
      DeliveryAddress,
      bigint,
      BasketType,
      Size,
      PackType,
      [] | [string],
    ],
    Order
  >,
  'filterGiftPacks' : ActorMethod<[CatalogFilters], Array<GiftPack>>,
  'getAllGiftPacks' : ActorMethod<[], Array<GiftPack>>,
  'getCart' : ActorMethod<[], [] | [Cart]>,
  'getGiftPackById' : ActorMethod<[string], [] | [GiftPack]>,
  'getOrderHistory' : ActorMethod<[], Array<Order>>,
  'getOrderHistoryForPrincipal' : ActorMethod<[Principal], Array<Order>>,
  'getUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'initialize' : ActorMethod<[], undefined>,
  'saveCart' : ActorMethod<[Cart], undefined>,
  'searchGiftPacks' : ActorMethod<[string], Array<GiftPack>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];