/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BasketType = { 'woodenCrate' : null } |
  { 'wickerBasket' : null } |
  { 'giftBox' : null };
export interface Cart {
  'basketType' : BasketType,
  'userId' : string,
  'packingType' : PackType,
  'size' : Size,
  'messageCard' : [] | [string],
  'items' : Array<CartItem>,
}
export interface CartItem {
  'wrappingOption' : [] | [string],
  'customMessage' : [] | [string],
  'quantity' : bigint,
  'packId' : string,
}
export interface CatalogFilters {
  'outOfStock' : [] | [boolean],
  'priceRange' : [] | [{ 'max' : bigint, 'min' : bigint }],
  'searchTerm' : [] | [string],
  'category' : [] | [CategoryType],
}
export interface Category { 'name' : string, 'description' : string }
export type CategoryType = { 'anniversary' : null } |
  { 'custom' : null } |
  { 'festive' : null } |
  { 'birthday' : null } |
  { 'wellness' : null } |
  { 'sympathy' : null } |
  { 'corporate' : null };
export interface ContactSubmission {
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : Time,
  'phone' : string,
}
export interface Coupon {
  'code' : string,
  'expirationDate' : Time,
  'discountPercentage' : bigint,
  'minDiscountPercentage' : [] | [bigint],
  'remainingQuantity' : bigint,
  'totalQuantity' : bigint,
  'maxDiscountAmount' : [] | [bigint],
}
export interface DeliveryAddress {
  'id' : string,
  'street' : string,
  'city' : string,
  'name' : string,
  'state' : string,
  'phone' : string,
  'pincode' : string,
}
export type ExternalBlob = Uint8Array;
export interface GiftItem {
  'id' : string,
  'name' : string,
  'description' : string,
  'category' : CategoryType,
  'price' : bigint,
  'images' : Array<ExternalBlob>,
}
export interface GiftPack {
  'id' : string,
  'basketType' : BasketType,
  'title' : string,
  'size' : Size,
  'description' : string,
  'discount' : bigint,
  'category' : CategoryType,
  'items' : Array<GiftItem>,
  'price' : bigint,
  'images' : Array<ExternalBlob>,
}
export interface Order {
  'id' : string,
  'basketType' : BasketType,
  'status' : OrderStatus,
  'deliveryAddress' : DeliveryAddress,
  'userId' : string,
  'packingType' : PackType,
  'createdAt' : Time,
  'size' : Size,
  'messageCard' : [] | [string],
  'totalAmount' : bigint,
  'paymentId' : string,
  'items' : Array<CartItem>,
}
export type OrderStatus = { 'shipped' : null } |
  { 'cancelled' : null } |
  { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export type PackType = { 'ribbonColor1' : null } |
  { 'ribbonColor2' : null } |
  { 'wrapStyle1' : null } |
  { 'wrapStyle2' : null };
export interface Product {
  'id' : string,
  'name' : string,
  'description' : string,
  'category' : CategoryType,
  'price' : bigint,
  'images' : Array<string>,
}
export interface RazorpayPayment {
  'status' : string,
  'paymentId' : string,
  'payer' : Principal,
  'amount' : bigint,
}
export type Size = { 'large' : null } |
  { 'small' : null } |
  { 'medium' : null };
export type Time = bigint;
export interface UserProfile {
  'principal' : Principal,
  'name' : string,
  'email' : string,
  'phone' : string,
  'pincode' : string,
  'defaultAddress' : DeliveryAddress,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminUpdateOrderStatus' : ActorMethod<[string, OrderStatus], undefined>,
  'adminViewAllOrders' : ActorMethod<[], Array<Order>>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'clearCart' : ActorMethod<[], undefined>,
  'createCategory' : ActorMethod<[string, string], Category>,
  'createCoupon' : ActorMethod<
    [string, bigint, [] | [bigint], [] | [bigint], Time, bigint],
    Coupon
  >,
  'createGiftPack' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      bigint,
      CategoryType,
      Array<GiftItem>,
      Array<ExternalBlob>,
      BasketType,
      Size,
    ],
    GiftPack
  >,
  'createOrUpdateUserProfile' : ActorMethod<
    [string, string, string, DeliveryAddress, string],
    UserProfile
  >,
  'createOrder' : ActorMethod<
    [
      string,
      Array<CartItem>,
      DeliveryAddress,
      bigint,
      BasketType,
      Size,
      PackType,
      [] | [string],
      string,
      [] | [string],
    ],
    Order
  >,
  'createProduct' : ActorMethod<
    [string, string, string, bigint, CategoryType, Array<string>],
    Product
  >,
  'deleteGiftPack' : ActorMethod<[string], undefined>,
  'filterGiftPacks' : ActorMethod<[CatalogFilters], Array<GiftPack>>,
  'getAllCategories' : ActorMethod<[], Array<Category>>,
  'getAllGiftPacks' : ActorMethod<[], Array<GiftPack>>,
  'getAllPayments' : ActorMethod<[], Array<RazorpayPayment>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCart' : ActorMethod<[], [] | [Cart]>,
  'getContactSubmissions' : ActorMethod<[], Array<ContactSubmission>>,
  'getGiftPackById' : ActorMethod<[string], [] | [GiftPack]>,
  'getOrderHistory' : ActorMethod<[], Array<Order>>,
  'getOrderHistoryForPrincipal' : ActorMethod<[Principal], Array<Order>>,
  'getProductById' : ActorMethod<[string], [] | [Product]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'initialize' : ActorMethod<[], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isPincodeServiceable' : ActorMethod<[string], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveCart' : ActorMethod<[Cart], undefined>,
  'searchGiftPacks' : ActorMethod<[string], Array<GiftPack>>,
  'storePayment' : ActorMethod<[string, bigint, string], RazorpayPayment>,
  'submitContactForm' : ActorMethod<
    [string, string, string, string],
    undefined
  >,
  'updateCartItemQuantity' : ActorMethod<[string, bigint], [] | [Cart]>,
  'updateGiftPack' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      bigint,
      CategoryType,
      Array<GiftItem>,
      Array<ExternalBlob>,
      BasketType,
      Size,
    ],
    GiftPack
  >,
  'updateProduct' : ActorMethod<
    [string, string, string, bigint, CategoryType, Array<string>],
    Product
  >,
  'validateCoupon' : ActorMethod<[string], Coupon>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];