/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Category = IDL.Record({
  'name' : IDL.Text,
  'description' : IDL.Text,
});
export const Time = IDL.Int;
export const Coupon = IDL.Record({
  'code' : IDL.Text,
  'expirationDate' : Time,
  'discountPercentage' : IDL.Nat,
  'minDiscountPercentage' : IDL.Opt(IDL.Nat),
  'remainingQuantity' : IDL.Nat,
  'totalQuantity' : IDL.Nat,
  'maxDiscountAmount' : IDL.Opt(IDL.Nat),
});
export const CategoryType = IDL.Variant({
  'anniversary' : IDL.Null,
  'custom' : IDL.Null,
  'festive' : IDL.Null,
  'birthday' : IDL.Null,
  'wellness' : IDL.Null,
  'sympathy' : IDL.Null,
  'corporate' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const GiftItem = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : CategoryType,
  'price' : IDL.Int,
  'images' : IDL.Vec(ExternalBlob),
});
export const BasketType = IDL.Variant({
  'woodenCrate' : IDL.Null,
  'wickerBasket' : IDL.Null,
  'giftBox' : IDL.Null,
});
export const Size = IDL.Variant({
  'large' : IDL.Null,
  'small' : IDL.Null,
  'medium' : IDL.Null,
});
export const GiftPack = IDL.Record({
  'id' : IDL.Text,
  'basketType' : BasketType,
  'title' : IDL.Text,
  'size' : Size,
  'description' : IDL.Text,
  'discount' : IDL.Nat,
  'category' : CategoryType,
  'items' : IDL.Vec(GiftItem),
  'price' : IDL.Int,
  'images' : IDL.Vec(ExternalBlob),
});
export const DeliveryAddress = IDL.Record({
  'id' : IDL.Text,
  'street' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'state' : IDL.Text,
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
  'defaultAddress' : DeliveryAddress,
});
export const CartItem = IDL.Record({
  'wrappingOption' : IDL.Opt(IDL.Text),
  'customMessage' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Nat,
  'packId' : IDL.Text,
});
export const PackType = IDL.Variant({
  'ribbonColor1' : IDL.Null,
  'ribbonColor2' : IDL.Null,
  'wrapStyle1' : IDL.Null,
  'wrapStyle2' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Order = IDL.Record({
  'id' : IDL.Text,
  'basketType' : BasketType,
  'status' : OrderStatus,
  'deliveryAddress' : DeliveryAddress,
  'userId' : IDL.Text,
  'packingType' : PackType,
  'createdAt' : Time,
  'size' : Size,
  'messageCard' : IDL.Opt(IDL.Text),
  'totalAmount' : IDL.Int,
  'paymentId' : IDL.Text,
  'items' : IDL.Vec(CartItem),
});
export const Product = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : CategoryType,
  'price' : IDL.Int,
  'images' : IDL.Vec(IDL.Text),
});
export const CatalogFilters = IDL.Record({
  'outOfStock' : IDL.Opt(IDL.Bool),
  'priceRange' : IDL.Opt(IDL.Record({ 'max' : IDL.Int, 'min' : IDL.Int })),
  'searchTerm' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(CategoryType),
});
export const Cart = IDL.Record({
  'basketType' : BasketType,
  'userId' : IDL.Text,
  'packingType' : PackType,
  'size' : Size,
  'messageCard' : IDL.Opt(IDL.Text),
  'items' : IDL.Vec(CartItem),
});
export const ContactSubmission = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'phone' : IDL.Text,
});
export const RazorpayPayment = IDL.Record({
  'status' : IDL.Text,
  'paymentId' : IDL.Text,
  'payer' : IDL.Principal,
  'amount' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'clearCart' : IDL.Func([], [], []),
  'createCategory' : IDL.Func([IDL.Text, IDL.Text], [Category], []),
  'createCoupon' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat), Time, IDL.Nat],
      [Coupon],
      [],
    ),
  'createGiftPack' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Nat,
        CategoryType,
        IDL.Vec(GiftItem),
        IDL.Vec(ExternalBlob),
        BasketType,
        Size,
      ],
      [GiftPack],
      [],
    ),
  'createOrUpdateUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, DeliveryAddress, IDL.Text],
      [UserProfile],
      [],
    ),
  'createOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Vec(CartItem),
        DeliveryAddress,
        IDL.Int,
        BasketType,
        Size,
        PackType,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [Order],
      [],
    ),
  'createProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Int, CategoryType, IDL.Vec(IDL.Text)],
      [Product],
      [],
    ),
  'decrementCouponQuantity' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'deleteGiftPack' : IDL.Func([IDL.Text], [], []),
  'filterGiftPacks' : IDL.Func(
      [CatalogFilters],
      [IDL.Vec(GiftPack)],
      ['query'],
    ),
  'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getAllGiftPacks' : IDL.Func([], [IDL.Vec(GiftPack)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getCart' : IDL.Func([], [IDL.Opt(Cart)], ['query']),
  'getContactSubmissions' : IDL.Func(
      [],
      [IDL.Vec(ContactSubmission)],
      ['query'],
    ),
  'getGiftPackById' : IDL.Func([IDL.Text], [IDL.Opt(GiftPack)], ['query']),
  'getOrderHistory' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrderHistoryForPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Order)],
      ['query'],
    ),
  'getProductById' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'initialize' : IDL.Func([], [], []),
  'isPincodeServiceable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'recordCouponUsage' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCart' : IDL.Func([Cart], [], []),
  'searchGiftPacks' : IDL.Func([IDL.Text], [IDL.Vec(GiftPack)], ['query']),
  'storePayment' : IDL.Func(
      [IDL.Text, IDL.Int, IDL.Text],
      [RazorpayPayment],
      [],
    ),
  'submitContactForm' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [],
      [],
    ),
  'updateCartItemQuantity' : IDL.Func([IDL.Text, IDL.Nat], [IDL.Opt(Cart)], []),
  'updateGiftPack' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Int,
        IDL.Nat,
        CategoryType,
        IDL.Vec(GiftItem),
        IDL.Vec(ExternalBlob),
        BasketType,
        Size,
      ],
      [GiftPack],
      [],
    ),
  'updateProduct' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Int, CategoryType, IDL.Vec(IDL.Text)],
      [Product],
      [],
    ),
  'validateCoupon' : IDL.Func([IDL.Text], [Coupon], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Category = IDL.Record({ 'name' : IDL.Text, 'description' : IDL.Text });
  const Time = IDL.Int;
  const Coupon = IDL.Record({
    'code' : IDL.Text,
    'expirationDate' : Time,
    'discountPercentage' : IDL.Nat,
    'minDiscountPercentage' : IDL.Opt(IDL.Nat),
    'remainingQuantity' : IDL.Nat,
    'totalQuantity' : IDL.Nat,
    'maxDiscountAmount' : IDL.Opt(IDL.Nat),
  });
  const CategoryType = IDL.Variant({
    'anniversary' : IDL.Null,
    'custom' : IDL.Null,
    'festive' : IDL.Null,
    'birthday' : IDL.Null,
    'wellness' : IDL.Null,
    'sympathy' : IDL.Null,
    'corporate' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const GiftItem = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : CategoryType,
    'price' : IDL.Int,
    'images' : IDL.Vec(ExternalBlob),
  });
  const BasketType = IDL.Variant({
    'woodenCrate' : IDL.Null,
    'wickerBasket' : IDL.Null,
    'giftBox' : IDL.Null,
  });
  const Size = IDL.Variant({
    'large' : IDL.Null,
    'small' : IDL.Null,
    'medium' : IDL.Null,
  });
  const GiftPack = IDL.Record({
    'id' : IDL.Text,
    'basketType' : BasketType,
    'title' : IDL.Text,
    'size' : Size,
    'description' : IDL.Text,
    'discount' : IDL.Nat,
    'category' : CategoryType,
    'items' : IDL.Vec(GiftItem),
    'price' : IDL.Int,
    'images' : IDL.Vec(ExternalBlob),
  });
  const DeliveryAddress = IDL.Record({
    'id' : IDL.Text,
    'street' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'state' : IDL.Text,
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
    'defaultAddress' : DeliveryAddress,
  });
  const CartItem = IDL.Record({
    'wrappingOption' : IDL.Opt(IDL.Text),
    'customMessage' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Nat,
    'packId' : IDL.Text,
  });
  const PackType = IDL.Variant({
    'ribbonColor1' : IDL.Null,
    'ribbonColor2' : IDL.Null,
    'wrapStyle1' : IDL.Null,
    'wrapStyle2' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Order = IDL.Record({
    'id' : IDL.Text,
    'basketType' : BasketType,
    'status' : OrderStatus,
    'deliveryAddress' : DeliveryAddress,
    'userId' : IDL.Text,
    'packingType' : PackType,
    'createdAt' : Time,
    'size' : Size,
    'messageCard' : IDL.Opt(IDL.Text),
    'totalAmount' : IDL.Int,
    'paymentId' : IDL.Text,
    'items' : IDL.Vec(CartItem),
  });
  const Product = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : CategoryType,
    'price' : IDL.Int,
    'images' : IDL.Vec(IDL.Text),
  });
  const CatalogFilters = IDL.Record({
    'outOfStock' : IDL.Opt(IDL.Bool),
    'priceRange' : IDL.Opt(IDL.Record({ 'max' : IDL.Int, 'min' : IDL.Int })),
    'searchTerm' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(CategoryType),
  });
  const Cart = IDL.Record({
    'basketType' : BasketType,
    'userId' : IDL.Text,
    'packingType' : PackType,
    'size' : Size,
    'messageCard' : IDL.Opt(IDL.Text),
    'items' : IDL.Vec(CartItem),
  });
  const ContactSubmission = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'phone' : IDL.Text,
  });
  const RazorpayPayment = IDL.Record({
    'status' : IDL.Text,
    'paymentId' : IDL.Text,
    'payer' : IDL.Principal,
    'amount' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'clearCart' : IDL.Func([], [], []),
    'createCategory' : IDL.Func([IDL.Text, IDL.Text], [Category], []),
    'createCoupon' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat), Time, IDL.Nat],
        [Coupon],
        [],
      ),
    'createGiftPack' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Nat,
          CategoryType,
          IDL.Vec(GiftItem),
          IDL.Vec(ExternalBlob),
          BasketType,
          Size,
        ],
        [GiftPack],
        [],
      ),
    'createOrUpdateUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, DeliveryAddress, IDL.Text],
        [UserProfile],
        [],
      ),
    'createOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Vec(CartItem),
          DeliveryAddress,
          IDL.Int,
          BasketType,
          Size,
          PackType,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [Order],
        [],
      ),
    'createProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          CategoryType,
          IDL.Vec(IDL.Text),
        ],
        [Product],
        [],
      ),
    'decrementCouponQuantity' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'deleteGiftPack' : IDL.Func([IDL.Text], [], []),
    'filterGiftPacks' : IDL.Func(
        [CatalogFilters],
        [IDL.Vec(GiftPack)],
        ['query'],
      ),
    'getAllCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getAllGiftPacks' : IDL.Func([], [IDL.Vec(GiftPack)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getCart' : IDL.Func([], [IDL.Opt(Cart)], ['query']),
    'getContactSubmissions' : IDL.Func(
        [],
        [IDL.Vec(ContactSubmission)],
        ['query'],
      ),
    'getGiftPackById' : IDL.Func([IDL.Text], [IDL.Opt(GiftPack)], ['query']),
    'getOrderHistory' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrderHistoryForPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getProductById' : IDL.Func([IDL.Text], [IDL.Opt(Product)], ['query']),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'initialize' : IDL.Func([], [], []),
    'isPincodeServiceable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'recordCouponUsage' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCart' : IDL.Func([Cart], [], []),
    'searchGiftPacks' : IDL.Func([IDL.Text], [IDL.Vec(GiftPack)], ['query']),
    'storePayment' : IDL.Func(
        [IDL.Text, IDL.Int, IDL.Text],
        [RazorpayPayment],
        [],
      ),
    'submitContactForm' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [],
        [],
      ),
    'updateCartItemQuantity' : IDL.Func(
        [IDL.Text, IDL.Nat],
        [IDL.Opt(Cart)],
        [],
      ),
    'updateGiftPack' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          IDL.Nat,
          CategoryType,
          IDL.Vec(GiftItem),
          IDL.Vec(ExternalBlob),
          BasketType,
          Size,
        ],
        [GiftPack],
        [],
      ),
    'updateProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Int,
          CategoryType,
          IDL.Vec(IDL.Text),
        ],
        [Product],
        [],
      ),
    'validateCoupon' : IDL.Func([IDL.Text], [Coupon], []),
  });
};

export const init = ({ IDL }) => { return []; };