/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const DeliveryAddress = IDL.Record({
  'id' : IDL.Text,
  'street' : IDL.Text,
  'city' : IDL.Text,
  'name' : IDL.Text,
  'state' : IDL.Text,
  'phone' : IDL.Text,
  'pincode' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'phone' : IDL.Text,
  'defaultAddress' : DeliveryAddress,
});
export const CartItem = IDL.Record({
  'wrappingOption' : IDL.Opt(IDL.Text),
  'customMessage' : IDL.Opt(IDL.Text),
  'quantity' : IDL.Nat,
  'packId' : IDL.Text,
});
export const BasketType = IDL.Variant({
  'woodenCrate' : IDL.Null,
  'wickerBasket' : IDL.Null,
  'giftBox' : IDL.Null,
});
export const Size = IDL.Variant({
  'large' : IDL.Null,
  'small' : IDL.Null,
  'medium' : IDL.Null,
});
export const PackType = IDL.Variant({
  'ribbonColor1' : IDL.Null,
  'ribbonColor2' : IDL.Null,
  'wrapStyle1' : IDL.Null,
  'wrapStyle2' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'shipped' : IDL.Null,
  'cancelled' : IDL.Null,
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Time = IDL.Int;
export const Order = IDL.Record({
  'id' : IDL.Text,
  'basketType' : BasketType,
  'status' : OrderStatus,
  'deliveryAddress' : DeliveryAddress,
  'userId' : IDL.Text,
  'packingType' : PackType,
  'createdAt' : Time,
  'size' : Size,
  'messageCard' : IDL.Opt(IDL.Text),
  'totalAmount' : IDL.Int,
  'items' : IDL.Vec(CartItem),
});
export const Category = IDL.Variant({
  'anniversary' : IDL.Null,
  'custom' : IDL.Null,
  'festive' : IDL.Null,
  'birthday' : IDL.Null,
  'wellness' : IDL.Null,
  'sympathy' : IDL.Null,
  'corporate' : IDL.Null,
});
export const CatalogFilters = IDL.Record({
  'outOfStock' : IDL.Opt(IDL.Bool),
  'priceRange' : IDL.Opt(IDL.Record({ 'max' : IDL.Int, 'min' : IDL.Int })),
  'searchTerm' : IDL.Opt(IDL.Text),
  'category' : IDL.Opt(Category),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const GiftItem = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : Category,
  'price' : IDL.Int,
  'images' : IDL.Vec(ExternalBlob),
});
export const GiftPack = IDL.Record({
  'id' : IDL.Text,
  'basketType' : BasketType,
  'title' : IDL.Text,
  'size' : Size,
  'description' : IDL.Text,
  'category' : Category,
  'items' : IDL.Vec(GiftItem),
  'price' : IDL.Int,
  'images' : IDL.Vec(ExternalBlob),
});
export const Cart = IDL.Record({
  'basketType' : BasketType,
  'userId' : IDL.Text,
  'packingType' : PackType,
  'size' : Size,
  'messageCard' : IDL.Opt(IDL.Text),
  'items' : IDL.Vec(CartItem),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'clearCart' : IDL.Func([], [], []),
  'createOrUpdateUserProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, DeliveryAddress],
      [UserProfile],
      [],
    ),
  'createOrder' : IDL.Func(
      [
        IDL.Text,
        IDL.Vec(CartItem),
        DeliveryAddress,
        IDL.Int,
        BasketType,
        Size,
        PackType,
        IDL.Opt(IDL.Text),
      ],
      [Order],
      [],
    ),
  'filterGiftPacks' : IDL.Func(
      [CatalogFilters],
      [IDL.Vec(GiftPack)],
      ['query'],
    ),
  'getAllGiftPacks' : IDL.Func([], [IDL.Vec(GiftPack)], ['query']),
  'getCart' : IDL.Func([], [IDL.Opt(Cart)], ['query']),
  'getGiftPackById' : IDL.Func([IDL.Text], [IDL.Opt(GiftPack)], ['query']),
  'getOrderHistory' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getOrderHistoryForPrincipal' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(Order)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'initialize' : IDL.Func([], [], []),
  'saveCart' : IDL.Func([Cart], [], []),
  'searchGiftPacks' : IDL.Func([IDL.Text], [IDL.Vec(GiftPack)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const DeliveryAddress = IDL.Record({
    'id' : IDL.Text,
    'street' : IDL.Text,
    'city' : IDL.Text,
    'name' : IDL.Text,
    'state' : IDL.Text,
    'phone' : IDL.Text,
    'pincode' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
    'defaultAddress' : DeliveryAddress,
  });
  const CartItem = IDL.Record({
    'wrappingOption' : IDL.Opt(IDL.Text),
    'customMessage' : IDL.Opt(IDL.Text),
    'quantity' : IDL.Nat,
    'packId' : IDL.Text,
  });
  const BasketType = IDL.Variant({
    'woodenCrate' : IDL.Null,
    'wickerBasket' : IDL.Null,
    'giftBox' : IDL.Null,
  });
  const Size = IDL.Variant({
    'large' : IDL.Null,
    'small' : IDL.Null,
    'medium' : IDL.Null,
  });
  const PackType = IDL.Variant({
    'ribbonColor1' : IDL.Null,
    'ribbonColor2' : IDL.Null,
    'wrapStyle1' : IDL.Null,
    'wrapStyle2' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'shipped' : IDL.Null,
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Time = IDL.Int;
  const Order = IDL.Record({
    'id' : IDL.Text,
    'basketType' : BasketType,
    'status' : OrderStatus,
    'deliveryAddress' : DeliveryAddress,
    'userId' : IDL.Text,
    'packingType' : PackType,
    'createdAt' : Time,
    'size' : Size,
    'messageCard' : IDL.Opt(IDL.Text),
    'totalAmount' : IDL.Int,
    'items' : IDL.Vec(CartItem),
  });
  const Category = IDL.Variant({
    'anniversary' : IDL.Null,
    'custom' : IDL.Null,
    'festive' : IDL.Null,
    'birthday' : IDL.Null,
    'wellness' : IDL.Null,
    'sympathy' : IDL.Null,
    'corporate' : IDL.Null,
  });
  const CatalogFilters = IDL.Record({
    'outOfStock' : IDL.Opt(IDL.Bool),
    'priceRange' : IDL.Opt(IDL.Record({ 'max' : IDL.Int, 'min' : IDL.Int })),
    'searchTerm' : IDL.Opt(IDL.Text),
    'category' : IDL.Opt(Category),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const GiftItem = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : Category,
    'price' : IDL.Int,
    'images' : IDL.Vec(ExternalBlob),
  });
  const GiftPack = IDL.Record({
    'id' : IDL.Text,
    'basketType' : BasketType,
    'title' : IDL.Text,
    'size' : Size,
    'description' : IDL.Text,
    'category' : Category,
    'items' : IDL.Vec(GiftItem),
    'price' : IDL.Int,
    'images' : IDL.Vec(ExternalBlob),
  });
  const Cart = IDL.Record({
    'basketType' : BasketType,
    'userId' : IDL.Text,
    'packingType' : PackType,
    'size' : Size,
    'messageCard' : IDL.Opt(IDL.Text),
    'items' : IDL.Vec(CartItem),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'clearCart' : IDL.Func([], [], []),
    'createOrUpdateUserProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, DeliveryAddress],
        [UserProfile],
        [],
      ),
    'createOrder' : IDL.Func(
        [
          IDL.Text,
          IDL.Vec(CartItem),
          DeliveryAddress,
          IDL.Int,
          BasketType,
          Size,
          PackType,
          IDL.Opt(IDL.Text),
        ],
        [Order],
        [],
      ),
    'filterGiftPacks' : IDL.Func(
        [CatalogFilters],
        [IDL.Vec(GiftPack)],
        ['query'],
      ),
    'getAllGiftPacks' : IDL.Func([], [IDL.Vec(GiftPack)], ['query']),
    'getCart' : IDL.Func([], [IDL.Opt(Cart)], ['query']),
    'getGiftPackById' : IDL.Func([IDL.Text], [IDL.Opt(GiftPack)], ['query']),
    'getOrderHistory' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getOrderHistoryForPrincipal' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Order)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'initialize' : IDL.Func([], [], []),
    'saveCart' : IDL.Func([Cart], [], []),
    'searchGiftPacks' : IDL.Func([IDL.Text], [IDL.Vec(GiftPack)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };