/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface GiftItem {
    id: string;
    name: string;
    description: string;
    category: CategoryType;
    price: bigint;
    images: Array<ExternalBlob>;
}
export interface UserProfile {
    principal: Principal;
    name: string;
    email: string;
    phone: string;
    pincode: string;
    defaultAddress: DeliveryAddress;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type Time = bigint;
export interface Category {
    name: string;
    description: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface Coupon {
    code: string;
    expirationDate: Time;
    discountPercentage: bigint;
    minDiscountPercentage?: bigint;
    remainingQuantity: bigint;
    totalQuantity: bigint;
    maxDiscountAmount?: bigint;
}
export interface ContactSubmission {
    name: string;
    email: string;
    message: string;
    timestamp: Time;
    phone: string;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface CatalogFilters {
    outOfStock?: boolean;
    priceRange?: {
        max: bigint;
        min: bigint;
    };
    searchTerm?: string;
    category?: CategoryType;
}
export interface Order {
    id: string;
    basketType: BasketType;
    status: OrderStatus;
    deliveryAddress: DeliveryAddress;
    userId: string;
    packingType: PackType;
    createdAt: Time;
    size: Size;
    messageCard?: string;
    totalAmount: bigint;
    paymentId: string;
    items: Array<CartItem>;
}
export interface Cart {
    basketType: BasketType;
    userId: string;
    packingType: PackType;
    size: Size;
    messageCard?: string;
    items: Array<CartItem>;
}
export interface GiftPack {
    id: string;
    basketType: BasketType;
    title: string;
    size: Size;
    description: string;
    discount: bigint;
    category: CategoryType;
    items: Array<GiftItem>;
    price: bigint;
    images: Array<ExternalBlob>;
}
export interface DeliveryAddress {
    id: string;
    street: string;
    city: string;
    name: string;
    state: string;
    phone: string;
    pincode: string;
}
export interface CartItem {
    wrappingOption?: string;
    customMessage?: string;
    quantity: bigint;
    packId: string;
}
export interface RazorpayPayment {
    status: string;
    paymentId: string;
    payer: Principal;
    amount: bigint;
}
export interface Product {
    id: string;
    name: string;
    description: string;
    category: CategoryType;
    price: bigint;
    images: Array<string>;
}
export enum BasketType {
    woodenCrate = "woodenCrate",
    wickerBasket = "wickerBasket",
    giftBox = "giftBox"
}
export enum CategoryType {
    anniversary = "anniversary",
    custom = "custom",
    festive = "festive",
    birthday = "birthday",
    wellness = "wellness",
    sympathy = "sympathy",
    corporate = "corporate"
}
export enum OrderStatus {
    shipped = "shipped",
    cancelled = "cancelled",
    pending = "pending",
    delivered = "delivered",
    confirmed = "confirmed"
}
export enum PackType {
    ribbonColor1 = "ribbonColor1",
    ribbonColor2 = "ribbonColor2",
    wrapStyle1 = "wrapStyle1",
    wrapStyle2 = "wrapStyle2"
}
export enum Size {
    large = "large",
    small = "small",
    medium = "medium"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    clearCart(): Promise<void>;
    createCategory(name: string, description: string): Promise<Category>;
    createCoupon(code: string, discountPercentage: bigint, minDiscountPercentage: bigint | null, maxDiscountAmount: bigint | null, expirationDate: Time, totalQuantity: bigint): Promise<Coupon>;
    createGiftPack(id: string, title: string, description: string, price: bigint, discount: bigint, category: CategoryType, items: Array<GiftItem>, images: Array<ExternalBlob>, basketType: BasketType, size: Size): Promise<GiftPack>;
    createOrUpdateUserProfile(name: string, email: string, phone: string, address: DeliveryAddress, pincode: string): Promise<UserProfile>;
    createOrder(userId: string, items: Array<CartItem>, deliveryAddress: DeliveryAddress, totalAmount: bigint, basketType: BasketType, size: Size, packingType: PackType, messageCard: string | null, paymentId: string, couponCode: string | null): Promise<Order>;
    createProduct(id: string, name: string, description: string, price: bigint, category: CategoryType, images: Array<string>): Promise<Product>;
    deleteGiftPack(id: string): Promise<void>;
    filterGiftPacks(filters: CatalogFilters): Promise<Array<GiftPack>>;
    getAllCategories(): Promise<Array<Category>>;
    getAllGiftPacks(): Promise<Array<GiftPack>>;
    getAllProducts(): Promise<Array<Product>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getCart(): Promise<Cart | null>;
    getContactSubmissions(): Promise<Array<ContactSubmission>>;
    getGiftPackById(id: string): Promise<GiftPack | null>;
    getOrderHistory(): Promise<Array<Order>>;
    getOrderHistoryForPrincipal(recipient: Principal): Promise<Array<Order>>;
    getProductById(id: string): Promise<Product | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    initialize(): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    isPincodeServiceable(pincode: string): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveCart(cart: Cart): Promise<void>;
    searchGiftPacks(searchTerm: string): Promise<Array<GiftPack>>;
    storePayment(paymentId: string, amount: bigint, status: string): Promise<RazorpayPayment>;
    submitContactForm(name: string, email: string, phone: string, message: string): Promise<void>;
    updateCartItemQuantity(packId: string, newQuantity: bigint): Promise<Cart | null>;
    updateGiftPack(id: string, title: string, description: string, price: bigint, discount: bigint, category: CategoryType, items: Array<GiftItem>, images: Array<ExternalBlob>, basketType: BasketType, size: Size): Promise<GiftPack>;
    updateProduct(id: string, name: string, description: string, price: bigint, category: CategoryType, images: Array<string>): Promise<Product>;
    validateCoupon(code: string): Promise<Coupon>;
}
import type { BasketType as _BasketType, Cart as _Cart, CartItem as _CartItem, CatalogFilters as _CatalogFilters, CategoryType as _CategoryType, Coupon as _Coupon, DeliveryAddress as _DeliveryAddress, ExternalBlob as _ExternalBlob, GiftItem as _GiftItem, GiftPack as _GiftPack, Order as _Order, OrderStatus as _OrderStatus, PackType as _PackType, Product as _Product, Size as _Size, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearCart(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCart();
            return result;
        }
    }
    async createCategory(arg0: string, arg1: string): Promise<Category> {
        if (this.processError) {
            try {
                const result = await this.actor.createCategory(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCategory(arg0, arg1);
            return result;
        }
    }
    async createCoupon(arg0: string, arg1: bigint, arg2: bigint | null, arg3: bigint | null, arg4: Time, arg5: bigint): Promise<Coupon> {
        if (this.processError) {
            try {
                const result = await this.actor.createCoupon(arg0, arg1, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
                return from_candid_Coupon_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCoupon(arg0, arg1, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n10(this._uploadFile, this._downloadFile, arg3), arg4, arg5);
            return from_candid_Coupon_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async createGiftPack(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: CategoryType, arg6: Array<GiftItem>, arg7: Array<ExternalBlob>, arg8: BasketType, arg9: Size): Promise<GiftPack> {
        if (this.processError) {
            try {
                const result = await this.actor.createGiftPack(arg0, arg1, arg2, arg3, arg4, to_candid_CategoryType_n13(this._uploadFile, this._downloadFile, arg5), await to_candid_vec_n15(this._uploadFile, this._downloadFile, arg6), await to_candid_vec_n18(this._uploadFile, this._downloadFile, arg7), to_candid_BasketType_n20(this._uploadFile, this._downloadFile, arg8), to_candid_Size_n22(this._uploadFile, this._downloadFile, arg9));
                return from_candid_GiftPack_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createGiftPack(arg0, arg1, arg2, arg3, arg4, to_candid_CategoryType_n13(this._uploadFile, this._downloadFile, arg5), await to_candid_vec_n15(this._uploadFile, this._downloadFile, arg6), await to_candid_vec_n18(this._uploadFile, this._downloadFile, arg7), to_candid_BasketType_n20(this._uploadFile, this._downloadFile, arg8), to_candid_Size_n22(this._uploadFile, this._downloadFile, arg9));
            return from_candid_GiftPack_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async createOrUpdateUserProfile(arg0: string, arg1: string, arg2: string, arg3: DeliveryAddress, arg4: string): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrUpdateUserProfile(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrUpdateUserProfile(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createOrder(arg0: string, arg1: Array<CartItem>, arg2: DeliveryAddress, arg3: bigint, arg4: BasketType, arg5: Size, arg6: PackType, arg7: string | null, arg8: string, arg9: string | null): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.createOrder(arg0, to_candid_vec_n37(this._uploadFile, this._downloadFile, arg1), arg2, arg3, to_candid_BasketType_n20(this._uploadFile, this._downloadFile, arg4), to_candid_Size_n22(this._uploadFile, this._downloadFile, arg5), to_candid_PackType_n40(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n42(this._uploadFile, this._downloadFile, arg7), arg8, to_candid_opt_n42(this._uploadFile, this._downloadFile, arg9));
                return from_candid_Order_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createOrder(arg0, to_candid_vec_n37(this._uploadFile, this._downloadFile, arg1), arg2, arg3, to_candid_BasketType_n20(this._uploadFile, this._downloadFile, arg4), to_candid_Size_n22(this._uploadFile, this._downloadFile, arg5), to_candid_PackType_n40(this._uploadFile, this._downloadFile, arg6), to_candid_opt_n42(this._uploadFile, this._downloadFile, arg7), arg8, to_candid_opt_n42(this._uploadFile, this._downloadFile, arg9));
            return from_candid_Order_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProduct(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: CategoryType, arg5: Array<string>): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(arg0, arg1, arg2, arg3, to_candid_CategoryType_n13(this._uploadFile, this._downloadFile, arg4), arg5);
                return from_candid_Product_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(arg0, arg1, arg2, arg3, to_candid_CategoryType_n13(this._uploadFile, this._downloadFile, arg4), arg5);
            return from_candid_Product_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteGiftPack(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteGiftPack(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteGiftPack(arg0);
            return result;
        }
    }
    async filterGiftPacks(arg0: CatalogFilters): Promise<Array<GiftPack>> {
        if (this.processError) {
            try {
                const result = await this.actor.filterGiftPacks(to_candid_CatalogFilters_n55(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.filterGiftPacks(to_candid_CatalogFilters_n55(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCategories();
            return result;
        }
    }
    async getAllGiftPacks(): Promise<Array<GiftPack>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllGiftPacks();
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllGiftPacks();
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return from_candid_vec_n58(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCart(): Promise<Cart | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCart();
                return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCart();
            return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContactSubmissions(): Promise<Array<ContactSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContactSubmissions();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContactSubmissions();
            return result;
        }
    }
    async getGiftPackById(arg0: string): Promise<GiftPack | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getGiftPackById(arg0);
                return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getGiftPackById(arg0);
            return from_candid_opt_n65(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderHistory(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderHistory();
                return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderHistory();
            return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderHistoryForPrincipal(arg0: Principal): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderHistoryForPrincipal(arg0);
                return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderHistoryForPrincipal(arg0);
            return from_candid_vec_n66(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProductById(arg0: string): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProductById(arg0);
                return from_candid_opt_n67(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProductById(arg0);
            return from_candid_opt_n67(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n59(this._uploadFile, this._downloadFile, result);
        }
    }
    async initialize(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.initialize();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.initialize();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isPincodeServiceable(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isPincodeServiceable(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isPincodeServiceable(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveCart(arg0: Cart): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCart(to_candid_Cart_n68(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCart(to_candid_Cart_n68(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchGiftPacks(arg0: string): Promise<Array<GiftPack>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchGiftPacks(arg0);
                return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchGiftPacks(arg0);
            return from_candid_vec_n57(this._uploadFile, this._downloadFile, result);
        }
    }
    async storePayment(arg0: string, arg1: bigint, arg2: string): Promise<RazorpayPayment> {
        if (this.processError) {
            try {
                const result = await this.actor.storePayment(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.storePayment(arg0, arg1, arg2);
            return result;
        }
    }
    async submitContactForm(arg0: string, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitContactForm(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitContactForm(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateCartItemQuantity(arg0: string, arg1: bigint): Promise<Cart | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCartItemQuantity(arg0, arg1);
                return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCartItemQuantity(arg0, arg1);
            return from_candid_opt_n62(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateGiftPack(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: bigint, arg5: CategoryType, arg6: Array<GiftItem>, arg7: Array<ExternalBlob>, arg8: BasketType, arg9: Size): Promise<GiftPack> {
        if (this.processError) {
            try {
                const result = await this.actor.updateGiftPack(arg0, arg1, arg2, arg3, arg4, to_candid_CategoryType_n13(this._uploadFile, this._downloadFile, arg5), await to_candid_vec_n15(this._uploadFile, this._downloadFile, arg6), await to_candid_vec_n18(this._uploadFile, this._downloadFile, arg7), to_candid_BasketType_n20(this._uploadFile, this._downloadFile, arg8), to_candid_Size_n22(this._uploadFile, this._downloadFile, arg9));
                return from_candid_GiftPack_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateGiftPack(arg0, arg1, arg2, arg3, arg4, to_candid_CategoryType_n13(this._uploadFile, this._downloadFile, arg5), await to_candid_vec_n15(this._uploadFile, this._downloadFile, arg6), await to_candid_vec_n18(this._uploadFile, this._downloadFile, arg7), to_candid_BasketType_n20(this._uploadFile, this._downloadFile, arg8), to_candid_Size_n22(this._uploadFile, this._downloadFile, arg9));
            return from_candid_GiftPack_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateProduct(arg0: string, arg1: string, arg2: string, arg3: bigint, arg4: CategoryType, arg5: Array<string>): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3, to_candid_CategoryType_n13(this._uploadFile, this._downloadFile, arg4), arg5);
                return from_candid_Product_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3, to_candid_CategoryType_n13(this._uploadFile, this._downloadFile, arg4), arg5);
            return from_candid_Product_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async validateCoupon(arg0: string): Promise<Coupon> {
        if (this.processError) {
            try {
                const result = await this.actor.validateCoupon(arg0);
                return from_candid_Coupon_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateCoupon(arg0);
            return from_candid_Coupon_n11(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BasketType_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BasketType): BasketType {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_CartItem_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CartItem): CartItem {
    return from_candid_record_n52(_uploadFile, _downloadFile, value);
}
function from_candid_Cart_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cart): Cart {
    return from_candid_record_n64(_uploadFile, _downloadFile, value);
}
function from_candid_CategoryType_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CategoryType): CategoryType {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_Coupon_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Coupon): Coupon {
    return from_candid_record_n12(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_GiftItem_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GiftItem): Promise<GiftItem> {
    return await from_candid_record_n34(_uploadFile, _downloadFile, value);
}
async function from_candid_GiftPack_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _GiftPack): Promise<GiftPack> {
    return await from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_PackType_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PackType): PackType {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function from_candid_Product_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Product {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
function from_candid_Size_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Size): Size {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n61(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Cart]): Cart | null {
    return value.length === 0 ? null : from_candid_Cart_n63(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_GiftPack]): Promise<GiftPack | null> {
    return value.length === 0 ? null : await from_candid_GiftPack_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : from_candid_Product_n53(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    code: string;
    expirationDate: _Time;
    discountPercentage: bigint;
    minDiscountPercentage: [] | [bigint];
    remainingQuantity: bigint;
    totalQuantity: bigint;
    maxDiscountAmount: [] | [bigint];
}): {
    code: string;
    expirationDate: Time;
    discountPercentage: bigint;
    minDiscountPercentage?: bigint;
    remainingQuantity: bigint;
    totalQuantity: bigint;
    maxDiscountAmount?: bigint;
} {
    return {
        code: value.code,
        expirationDate: value.expirationDate,
        discountPercentage: value.discountPercentage,
        minDiscountPercentage: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.minDiscountPercentage)),
        remainingQuantity: value.remainingQuantity,
        totalQuantity: value.totalQuantity,
        maxDiscountAmount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.maxDiscountAmount))
    };
}
async function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    basketType: _BasketType;
    title: string;
    size: _Size;
    description: string;
    discount: bigint;
    category: _CategoryType;
    items: Array<_GiftItem>;
    price: bigint;
    images: Array<_ExternalBlob>;
}): Promise<{
    id: string;
    basketType: BasketType;
    title: string;
    size: Size;
    description: string;
    discount: bigint;
    category: CategoryType;
    items: Array<GiftItem>;
    price: bigint;
    images: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        basketType: from_candid_BasketType_n26(_uploadFile, _downloadFile, value.basketType),
        title: value.title,
        size: from_candid_Size_n28(_uploadFile, _downloadFile, value.size),
        description: value.description,
        discount: value.discount,
        category: from_candid_CategoryType_n30(_uploadFile, _downloadFile, value.category),
        items: await from_candid_vec_n32(_uploadFile, _downloadFile, value.items),
        price: value.price,
        images: await from_candid_vec_n35(_uploadFile, _downloadFile, value.images)
    };
}
async function from_candid_record_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    description: string;
    category: _CategoryType;
    price: bigint;
    images: Array<_ExternalBlob>;
}): Promise<{
    id: string;
    name: string;
    description: string;
    category: CategoryType;
    price: bigint;
    images: Array<ExternalBlob>;
}> {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        category: from_candid_CategoryType_n30(_uploadFile, _downloadFile, value.category),
        price: value.price,
        images: await from_candid_vec_n35(_uploadFile, _downloadFile, value.images)
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    basketType: _BasketType;
    status: _OrderStatus;
    deliveryAddress: _DeliveryAddress;
    userId: string;
    packingType: _PackType;
    createdAt: _Time;
    size: _Size;
    messageCard: [] | [string];
    totalAmount: bigint;
    paymentId: string;
    items: Array<_CartItem>;
}): {
    id: string;
    basketType: BasketType;
    status: OrderStatus;
    deliveryAddress: DeliveryAddress;
    userId: string;
    packingType: PackType;
    createdAt: Time;
    size: Size;
    messageCard?: string;
    totalAmount: bigint;
    paymentId: string;
    items: Array<CartItem>;
} {
    return {
        id: value.id,
        basketType: from_candid_BasketType_n26(_uploadFile, _downloadFile, value.basketType),
        status: from_candid_OrderStatus_n45(_uploadFile, _downloadFile, value.status),
        deliveryAddress: value.deliveryAddress,
        userId: value.userId,
        packingType: from_candid_PackType_n47(_uploadFile, _downloadFile, value.packingType),
        createdAt: value.createdAt,
        size: from_candid_Size_n28(_uploadFile, _downloadFile, value.size),
        messageCard: record_opt_to_undefined(from_candid_opt_n49(_uploadFile, _downloadFile, value.messageCard)),
        totalAmount: value.totalAmount,
        paymentId: value.paymentId,
        items: from_candid_vec_n50(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    wrappingOption: [] | [string];
    customMessage: [] | [string];
    quantity: bigint;
    packId: string;
}): {
    wrappingOption?: string;
    customMessage?: string;
    quantity: bigint;
    packId: string;
} {
    return {
        wrappingOption: record_opt_to_undefined(from_candid_opt_n49(_uploadFile, _downloadFile, value.wrappingOption)),
        customMessage: record_opt_to_undefined(from_candid_opt_n49(_uploadFile, _downloadFile, value.customMessage)),
        quantity: value.quantity,
        packId: value.packId
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    description: string;
    category: _CategoryType;
    price: bigint;
    images: Array<string>;
}): {
    id: string;
    name: string;
    description: string;
    category: CategoryType;
    price: bigint;
    images: Array<string>;
} {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        category: from_candid_CategoryType_n30(_uploadFile, _downloadFile, value.category),
        price: value.price,
        images: value.images
    };
}
function from_candid_record_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    basketType: _BasketType;
    userId: string;
    packingType: _PackType;
    size: _Size;
    messageCard: [] | [string];
    items: Array<_CartItem>;
}): {
    basketType: BasketType;
    userId: string;
    packingType: PackType;
    size: Size;
    messageCard?: string;
    items: Array<CartItem>;
} {
    return {
        basketType: from_candid_BasketType_n26(_uploadFile, _downloadFile, value.basketType),
        userId: value.userId,
        packingType: from_candid_PackType_n47(_uploadFile, _downloadFile, value.packingType),
        size: from_candid_Size_n28(_uploadFile, _downloadFile, value.size),
        messageCard: record_opt_to_undefined(from_candid_opt_n49(_uploadFile, _downloadFile, value.messageCard)),
        items: from_candid_vec_n50(_uploadFile, _downloadFile, value.items)
    };
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    woodenCrate: null;
} | {
    wickerBasket: null;
} | {
    giftBox: null;
}): BasketType {
    return "woodenCrate" in value ? BasketType.woodenCrate : "wickerBasket" in value ? BasketType.wickerBasket : "giftBox" in value ? BasketType.giftBox : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    large: null;
} | {
    small: null;
} | {
    medium: null;
}): Size {
    return "large" in value ? Size.large : "small" in value ? Size.small : "medium" in value ? Size.medium : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    anniversary: null;
} | {
    custom: null;
} | {
    festive: null;
} | {
    birthday: null;
} | {
    wellness: null;
} | {
    sympathy: null;
} | {
    corporate: null;
}): CategoryType {
    return "anniversary" in value ? CategoryType.anniversary : "custom" in value ? CategoryType.custom : "festive" in value ? CategoryType.festive : "birthday" in value ? CategoryType.birthday : "wellness" in value ? CategoryType.wellness : "sympathy" in value ? CategoryType.sympathy : "corporate" in value ? CategoryType.corporate : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    shipped: null;
} | {
    cancelled: null;
} | {
    pending: null;
} | {
    delivered: null;
} | {
    confirmed: null;
}): OrderStatus {
    return "shipped" in value ? OrderStatus.shipped : "cancelled" in value ? OrderStatus.cancelled : "pending" in value ? OrderStatus.pending : "delivered" in value ? OrderStatus.delivered : "confirmed" in value ? OrderStatus.confirmed : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ribbonColor1: null;
} | {
    ribbonColor2: null;
} | {
    wrapStyle1: null;
} | {
    wrapStyle2: null;
}): PackType {
    return "ribbonColor1" in value ? PackType.ribbonColor1 : "ribbonColor2" in value ? PackType.ribbonColor2 : "wrapStyle1" in value ? PackType.wrapStyle1 : "wrapStyle2" in value ? PackType.wrapStyle2 : value;
}
function from_candid_variant_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GiftItem>): Promise<Array<GiftItem>> {
    return await Promise.all(value.map(async (x)=>await from_candid_GiftItem_n33(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ExternalBlob>): Promise<Array<ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ExternalBlob_n36(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CartItem>): Array<CartItem> {
    return value.map((x)=>from_candid_CartItem_n51(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_GiftPack>): Promise<Array<GiftPack>> {
    return await Promise.all(value.map(async (x)=>await from_candid_GiftPack_n24(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Array<Product> {
    return value.map((x)=>from_candid_Product_n53(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n43(_uploadFile, _downloadFile, x));
}
function to_candid_BasketType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BasketType): _BasketType {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_CartItem_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CartItem): _CartItem {
    return to_candid_record_n39(_uploadFile, _downloadFile, value);
}
function to_candid_Cart_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Cart): _Cart {
    return to_candid_record_n69(_uploadFile, _downloadFile, value);
}
function to_candid_CatalogFilters_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CatalogFilters): _CatalogFilters {
    return to_candid_record_n56(_uploadFile, _downloadFile, value);
}
function to_candid_CategoryType_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CategoryType): _CategoryType {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_GiftItem_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: GiftItem): Promise<_GiftItem> {
    return await to_candid_record_n17(_uploadFile, _downloadFile, value);
}
function to_candid_PackType_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PackType): _PackType {
    return to_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function to_candid_Size_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Size): _Size {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    name: string;
    description: string;
    category: CategoryType;
    price: bigint;
    images: Array<ExternalBlob>;
}): Promise<{
    id: string;
    name: string;
    description: string;
    category: _CategoryType;
    price: bigint;
    images: Array<_ExternalBlob>;
}> {
    return {
        id: value.id,
        name: value.name,
        description: value.description,
        category: to_candid_CategoryType_n13(_uploadFile, _downloadFile, value.category),
        price: value.price,
        images: await to_candid_vec_n18(_uploadFile, _downloadFile, value.images)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_record_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    wrappingOption?: string;
    customMessage?: string;
    quantity: bigint;
    packId: string;
}): {
    wrappingOption: [] | [string];
    customMessage: [] | [string];
    quantity: bigint;
    packId: string;
} {
    return {
        wrappingOption: value.wrappingOption ? candid_some(value.wrappingOption) : candid_none(),
        customMessage: value.customMessage ? candid_some(value.customMessage) : candid_none(),
        quantity: value.quantity,
        packId: value.packId
    };
}
function to_candid_record_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    outOfStock?: boolean;
    priceRange?: {
        max: bigint;
        min: bigint;
    };
    searchTerm?: string;
    category?: CategoryType;
}): {
    outOfStock: [] | [boolean];
    priceRange: [] | [{
            max: bigint;
            min: bigint;
        }];
    searchTerm: [] | [string];
    category: [] | [_CategoryType];
} {
    return {
        outOfStock: value.outOfStock ? candid_some(value.outOfStock) : candid_none(),
        priceRange: value.priceRange ? candid_some(value.priceRange) : candid_none(),
        searchTerm: value.searchTerm ? candid_some(value.searchTerm) : candid_none(),
        category: value.category ? candid_some(to_candid_CategoryType_n13(_uploadFile, _downloadFile, value.category)) : candid_none()
    };
}
function to_candid_record_n69(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    basketType: BasketType;
    userId: string;
    packingType: PackType;
    size: Size;
    messageCard?: string;
    items: Array<CartItem>;
}): {
    basketType: _BasketType;
    userId: string;
    packingType: _PackType;
    size: _Size;
    messageCard: [] | [string];
    items: Array<_CartItem>;
} {
    return {
        basketType: to_candid_BasketType_n20(_uploadFile, _downloadFile, value.basketType),
        userId: value.userId,
        packingType: to_candid_PackType_n40(_uploadFile, _downloadFile, value.packingType),
        size: to_candid_Size_n22(_uploadFile, _downloadFile, value.size),
        messageCard: value.messageCard ? candid_some(value.messageCard) : candid_none(),
        items: to_candid_vec_n37(_uploadFile, _downloadFile, value.items)
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CategoryType): {
    anniversary: null;
} | {
    custom: null;
} | {
    festive: null;
} | {
    birthday: null;
} | {
    wellness: null;
} | {
    sympathy: null;
} | {
    corporate: null;
} {
    return value == CategoryType.anniversary ? {
        anniversary: null
    } : value == CategoryType.custom ? {
        custom: null
    } : value == CategoryType.festive ? {
        festive: null
    } : value == CategoryType.birthday ? {
        birthday: null
    } : value == CategoryType.wellness ? {
        wellness: null
    } : value == CategoryType.sympathy ? {
        sympathy: null
    } : value == CategoryType.corporate ? {
        corporate: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BasketType): {
    woodenCrate: null;
} | {
    wickerBasket: null;
} | {
    giftBox: null;
} {
    return value == BasketType.woodenCrate ? {
        woodenCrate: null
    } : value == BasketType.wickerBasket ? {
        wickerBasket: null
    } : value == BasketType.giftBox ? {
        giftBox: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Size): {
    large: null;
} | {
    small: null;
} | {
    medium: null;
} {
    return value == Size.large ? {
        large: null
    } : value == Size.small ? {
        small: null
    } : value == Size.medium ? {
        medium: null
    } : value;
}
function to_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PackType): {
    ribbonColor1: null;
} | {
    ribbonColor2: null;
} | {
    wrapStyle1: null;
} | {
    wrapStyle2: null;
} {
    return value == PackType.ribbonColor1 ? {
        ribbonColor1: null
    } : value == PackType.ribbonColor2 ? {
        ribbonColor2: null
    } : value == PackType.wrapStyle1 ? {
        wrapStyle1: null
    } : value == PackType.wrapStyle2 ? {
        wrapStyle2: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<GiftItem>): Promise<Array<_GiftItem>> {
    return await Promise.all(value.map(async (x)=>await to_candid_GiftItem_n16(_uploadFile, _downloadFile, x)));
}
async function to_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<ExternalBlob>): Promise<Array<_ExternalBlob>> {
    return await Promise.all(value.map(async (x)=>await to_candid_ExternalBlob_n19(_uploadFile, _downloadFile, x)));
}
function to_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<CartItem>): Array<_CartItem> {
    return value.map((x)=>to_candid_CartItem_n38(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
